# Generated by Django 3.0.6 on 2020-05-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='purchase_number',
            field=models.IntegerField(null=True),
        ),
    ]
