# Generated by Django 3.0.6 on 2020-06-02 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0007_auto_20200602_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя поставшика')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='отредактировано')),
            ],
            options={
                'verbose_name': 'поставка',
                'verbose_name_plural': 'поставки',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='StorehouseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(null=True, verbose_name='количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storehouse_items', to='shop.Product', verbose_name='продукт')),
                ('storehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storehouse.Storehouse', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
