# Generated by Django 3.0.6 on 2020-05-23 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='бренд')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='url бренд')),
            ],
            options={
                'verbose_name': 'бренд',
                'verbose_name_plural': 'бренды',
            },
        ),
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='тип стекла')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='url стекла')),
            ],
            options={
                'verbose_name': 'стекло',
                'verbose_name_plural': 'стекло',
            },
        ),
        migrations.CreateModel(
            name='MechanismType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='тип механизма')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'тип механизма',
                'verbose_name_plural': 'тип механизма',
            },
        ),
        migrations.CreateModel(
            name='WaterResistanceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='влагозащита')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='url влагозащиты')),
            ],
            options={
                'verbose_name': 'влагозащита',
                'verbose_name_plural': 'влагозащита',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='имя')),
                ('slug', models.SlugField(max_length=200, verbose_name='url продукта')),
                ('image', models.ImageField(blank=True, upload_to='shop/templates/img', verbose_name='изображение')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('dimension', models.CharField(max_length=200, null=True, verbose_name='размер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('stock', models.PositiveIntegerField(verbose_name='остатки')),
                ('available', models.BooleanField(default=True, verbose_name='доступность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='отредактировано')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Brand', verbose_name='категория')),
                ('glass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Glass', verbose_name='стекло')),
                ('mechanism_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.MechanismType', verbose_name='тип механизма')),
                ('water_resistance_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.WaterResistanceClass', verbose_name='влагозащита')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
