# Generated by Django 3.0.6 on 2020-05-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200529_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=100, verbose_name='количество'),
            preserve_default=False,
        ),
    ]
