# Generated by Django 3.0.6 on 2020-06-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimension',
            field=models.IntegerField(null=True, verbose_name='размер'),
        ),
        migrations.AlterField(
            model_name='waterresistanceclass',
            name='name',
            field=models.IntegerField(null=True, verbose_name='влагозащита'),
        ),
    ]
