# Generated by Django 3.0.6 on 2020-06-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200601_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimension',
            field=models.CharField(max_length=200, null=True, verbose_name='размер'),
        ),
        migrations.AlterField(
            model_name='waterresistanceclass',
            name='name',
            field=models.CharField(default=100, max_length=200, verbose_name='влагозащита'),
            preserve_default=False,
        ),
    ]
