# Generated by Django 3.0.6 on 2020-06-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200601_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterresistanceclass',
            name='name',
            field=models.IntegerField(verbose_name='влагозащита'),
        ),
    ]
