# Generated by Django 3.0.6 on 2020-06-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200602_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterresistanceclass',
            options={'ordering': ('name',), 'verbose_name': 'влагозащита', 'verbose_name_plural': 'влагозащита'},
        ),
    ]
