# Generated by Django 3.0.6 on 2020-05-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200529_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'состав заказа', 'verbose_name_plural': 'состав заказов'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_processed',
            field=models.BooleanField(default=False),
        ),
    ]
